### ISSUE TITLE
globaltick and requestAnimationframe

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#146]
I don't exactly understand globaltick. Who fires this? How often?

**Comment by aforemny** [comment]
Hi @berenddeboer, `globaltick` is fired from `elm-mdc.js` exactly once every time the `data-globaltick` attribute is set for the first frame.

It is used to raise an event on node insertion, such as when a component first renders. In some instances, it is also used to raise an event when the configuration of a component changes.

**Comment by berenddeboer** [comment]
Ah right, I'm sort of relying on this to do what requestAnimationFrame does. Can I assume the same behaviour?

**Comment by aforemny** [comment]
Yes, with the following two caveats:

- it might actually take 2 animation frames to fire instead of just 1 (I have not found this to be an issue)
- if you require two consecutive `globaltick` events, you will have to make sure that you are removing the `data-globaltick` attribute for at least one animation frame

Those are two limitations compared to requestAnimationFrame. But you can run a DOM decoder on an element that does not have a globally unique `id` attribute.

**Comment by berenddeboer** [comment]
Indeed, that should be fine. I implemented the FLIP approach to animation (what mdc seems to be switching to where possible) in Tab Bar in 0.42, and I just wanted to make sure there was at least 1 animation frame.
