### ISSUE TITLE
Menu: missing functionality

### ISSUE THREAD

**Issue by berenddeboer** [aforemny/elm-mdc#173]
Currently not implemented:

- [x] keyboard navigation. The way to do this I think is make sure the menu actually uses List.
- [x] ripples. We'll get this once we switch to lists.
- [x] [support for the selection group variant](https://material.io/develop/web/components/menus/).
- [x] role "menuitem" should be set on li element.
- [x] click outside of menu should close menu. I think this can be done along similar lines as detecting if focus leaves list, i.e. see the code here: https://github.com/xarvh/elm-onclickoutside/blob/master/src/Html/OnClickOutside.elm

**Comment by aforemny** [comment]
Hi @berenddeboer, I tried to improve Menu a bit and pushed some commits to master. I made Menu use List internally, so that gives us keyboard navigation and ripples. I also took care of the menu closing again when clicking outside. If I recall correctly, this is because of an Elm bug that would not update the subscription correctly. So I've worked around that by setting the subscription unconditionally and handling the condition's predicate to the update function.

What do you mean here by selection groups?

**Comment by berenddeboer** [comment]
Selection groups are [documented here](https://material.io/develop/web/components/menus/):

> Selection Group Menu
> Menus can contain a group of list items that can represent the selection state of elements within the group.
