### ISSUE TITLE
Card Example crashes compiler

### ISSUE THREAD

**Issue by j340m3** [aforemny/elm-mdc#258]
I tried to use Material.Cards in my project and when I try to compile it, the elm/compiler eats all ram and CPU. Here is what I did:

1. I started by copying the example out of src/Material/Cards and pasted it in an empty module. 
2. I added a `Model` and `Msg` accordingly as well as a `view` function which should just show the aforementioned example.
3. Then vscode kicked in and tried to compile the file, the compiler ate all CPU and ram and took forever (had to kill it). Beforehand the compiling process was finished in seconds.

Here my Code:
https://github.com/msquaredc/elm-coding/blob/db-refactor/src/Material/SimplifiedCard.elm
What I tried so far:

- Pull the newest version of elm-mdc and run make
- Make sure I have the newest elm version (0.19.0)
- `rm -R elm-stuff`

**Comment by j340m3** [comment]
My Bad. I forgot to lift the Mdc Message. When I replaced all occurences of Mdc by (lift<<Mdc) everything went fine. But damn thats hard to debug.

**Comment by aforemny** [comment]
Hi @j340m3, I am sorry for the frustration that you've experienced. You are right in figuring out that this has been a compiler bug and there is not much we can do about it.

However, would you be so kind as to make your source code SimplifiedCard.elm available again so that I can test whether this compiler bug is fixed in the upcoming 0.19.1 release of the Elm compiler? If it is not, I would like to file an issue so that this can be avoided.

Thanks!
