### ISSUE TITLE
Demo not working correctly due to wrong paths in page.html

### ISSUE THREAD

**Issue by eddex** [aforemny/elm-mdc#270]
I've noticed that the demo page doesn't work as it should.

Steps to reproduce:

- clone the repository
- `cd elm-mdc`
- `build.cmd`
- `cd demo`
- `elm make --optimize Demo.elm --output demo.js`
- `cd ..`
- `elm reactor`
- navigate to localhost:8000

Chrome (Brave):
![image](https://user-images.githubusercontent.com/5302085/67623003-6776ed80-f820-11e9-91bb-d55b413735a7.png)

Firefox:
![image](https://user-images.githubusercontent.com/5302085/67623014-82e1f880-f820-11e9-8258-36cefa143564.png)

**Comment by berenddeboer** [comment]
You will need to go to to `/build/index.html' I believe. So I run `make build-demo` and then load index.html in the build page: `http://localhost:8000/build/index.html`, and that seems to work fine.

I'm not very familiar with `elm reactor`, why would you use that on the demo page itself?

**Comment by aforemny** [comment]
Hi @eddex, as @berenddeboer stated our demo does not work with elm-reactor unfortunately.

The reason for that is that elm-reactor is strictly a tool for beginning Elm development. As soon as you have a more advanced application in the sense that you might require interaction with JavaScript (ports) or load external assets such as JavaScript or CSS files, you should eject from using elm-reactor. You can read up on how to do that [here](https://guide.elm-lang.org/install/elm.html#elm-make).

Since this library requires external assets to function (elm-mdc.js, material-components-web.css), we unfortunately cannot support elm-reactor.
