### ISSUE TITLE
Handling dispatching of events messages for `styled` elements

### ISSUE THREAD

**Issue by fbessou** [aforemny/elm-mdc#57]
Hi @aforemny.

It is possible to send two message on a single event when clicking on a button:

```elm
Button.view Mdc [123] model.mdc
    [ onClick Save
    , onClick CloseDialog
    ]
    [ text "Click me!"]
```

I would have expected the following snippet to work the same way but it only sends the second message:

```elm
styled div
    [ onClick Save
    , onClick CloseDialog
    ]
    [ text "Click me!"]
```

After investigation I discovered that in the first scenario it works because `render` function of `Material.Internal.Component` adds a `Lift` property to the property list of the rendered component (by using the `Material.Internal.Options.dispatch` helper): [corresponding code](https://github.com/aforemny/elm-mdc/blob/master/src/Material/Internal/Component.elm#L53)

When this property is present, events messages are [correctly dispatched](https://github.com/aforemny/elm-mdc/blob/master/src/Material/Internal/Dispatch.elm#L62) but there is currently no way to add this property for `styled` elements since the `dispatch` function is not exposed in the public API. This would be solved with:

```elm
styled div
    [ onClick Save
    , onClick CloseDialog
    , Options.dispatch Mdc
    ]
    [ text "Click me!"]
```

I tried exposing the `dispatch` function in the `Material.Options` module but that requires adding a dependency on the `Material` module which creates a circular dependency: it seems that `Material.Internal.GlobalEvents` imports `Material.Options` ([see here](https://github.com/aforemny/elm-mdc/blob/master/src/Material/Internal/GlobalEvents.elm#L14)) but I think it should be `Material.Internal.Options`.

There are probably alternatives to exposing the dispatch handler, for example, making `styled` take a `(Material.Msg m -> m )` argument:

```elm
styled = Options.styled Mdc

view =
    styled div
        [ onClick Save
        , onClick CloseDialog
        ]
        [ text "Click me!"]
```

**Comment by aforemny** [comment]
Hi @fbessou, thank you for your detailed investigation into this. You are exactly right.

The fact that you are able to send two `onClick` messages from `Button.view` is an (unintended) side-effect from the internal implementation. We use `Options.dispatch` to allow for two kinds of messages: "internal" and "user code".

Your example would be considered as two "user code" messages on the same event handler. Unfortunately, event dispatching as implemented in this library is not really ready to be user-facing. As you state here, it would make pure-view functions like `styled` unnecessarily complicated.

As having two user code messages on the same handler is not supported by Elm yet, and this library's Dispatch is not finalized yet, I will not add support for it just yet.

In the mean-time, the idiomatic way to handle your use-case would be to register only one event listener `onClick SaveAndCloseDialog` on `Options.styled`.

I will have to think about this again when I will revise the Ripple API because it is suffering from problems related to this. I am leaning towards making `Options.dispatch Mdc` available as you suggest, so I will keep this open for now.

**Comment by fbessou** [comment]
Thank you very much for your response !
Your explanation makes the implementation a lot clearer to me ! :)

**Comment by aforemny** [comment]
Actually, I think this is non-actionable since the use case is invalid (two user messages on a HTML node). I might add something like this if it turns out that Ripple needs that, but for now I cannot think of any use-case. So I will just close this.

Please re-open and let me know if there are use cases, or if I am missing something obvious here.
