### ISSUE TITLE
Assigning Option.attribute on native control rather than wrapping div

### ISSUE THREAD

**Issue by timcase** [aforemny/elm-mdc#58]
Is it possible to assign an attribute to a control and have the attribute apply to the native control rather than the wrapping div?

`RadioButton.view lift [0] model.mdc [Options.attribute (Html.attributes.id "myradio"] []]`

results in the id 'myradio' being applied to a div that wraps the radio input rather than the radio input itself. 

Standard behavior for radio buttons is that clicking on a the label of a radio button should also cause the radio button to be selected, the mechanism for making this happen in html is to assign an id to the radio input and then assign the same to the for attribute of the label:
`<input type="radio" id="myradio" />
<label for="myradio>One</label>`

Is there a syntax that let's me apply the id to the input itself?

**Comment by aforemny** [comment]
Hi @timcase, you should use `RadioButton.nativeControl : List (Options.Property () m) -> Property m`.

**Comment by aforemny** [comment]
PS. I am not sure RadioButtons will work as you would expect. The idea is to maintain the selected state yourself inside `Model`, and then set `RadioButton.selected` from view.

Since RadioButtons do not respond to user interaction -- if you do not set `RadioButton.selected`, they will not appear selected -- your ID approach might now out and you have to move that to Elm logic, in which case the ID becomes redundant.

Feel free to share any thoughts on this behvior!

**Comment by timcase** [comment]
Ahh yeah you're right, doing this is the wrong thing to do because while the radio button might look selected in the DOM, my underlying elm model state was not actually updated. What I really need to do rather than trying to add an id to the radio button is attach an onClick to the label.

In this brave new "don't touch the DOM" world I need to unlearn all the things I learned. Okay thanks.

Still though I'm happy to see the above syntax in case I want attach a class or id for css reasons....
