### ISSUE TITLE
Select works strange on demo

### ISSUE THREAD

**Issue by rofrol** [aforemny/elm-mdc#71]
![output](https://user-images.githubusercontent.com/28787/40128540-2695827e-5932-11e8-8ec8-24240bb5a7c9.gif)

Google Chrome 66.0.3359.170, OS X

**Comment by aforemny** [comment]
Hi @rofrol, thank you for reporting this.

The issue here is that the current implementation assumes that all scrolled HTML elements are positioned relatively.

It should be possible to lift this restriction.

In the meantime and if you need a workaround, put `css "position" "relative"` on any parent of the `Select.view` that may be scrolled.

**Comment by aforemny** [comment]
Hi @rofol,
I implemented the solution for this particular problem in (874fc2199be00d145655d160f0690d1342cf6528). There are still some other issues. Feel free to open another bug report! :)

**Comment by rofrol** [comment]
Thanks.

You mean there are other issues not reported yet?

**Comment by aforemny** [comment]
Exactly. For instance, I see that

(1) the select jumps on the closing animation when you do the first selection
(2) the menu does not position itself correctly within the viewport (it should never cross a viewport border) (that might be a bug of menu rather than select)

If you want me to possibly prioritize those issues over others, or maybe somebody else fixes them, it might be good to have an issue.
